
title: Lang Nie


#sidebar links
email: nielang@bjtu.edu.cn #kang_liao AT bjtu DOT edu DOT cn
#phone: 012 345 6789
#linkedin: alandoe
#website_zhihu: ZHIHU
#website_csdn: CSDN
website_google: Google Scholar
github: Github
my_cv: CV
port: 4001
#Update all the sections by editing the files inside _includes folder.

theme: jekyll-theme-cayman
